import {
  AssignmentOutlined,
  Business,
  FormatAlignLeft,
  Event,
  FilterCenterFocus,
  LocalOfferOutlined,
  ShortText,
  LooksOne,
  Check,
  List,
  ArrowDropDown as ArrowDropdown,
  LocationOn,
  People as PeopleIcon,
  Security as SecurityIcon,
  Group as GroupIcon,
  Draw as DrawIcon,
  AccessTime,
  BurstMode,
  ViewList as ViewListIcon,
  AddLink,
  DateRange,
  LocalOffer as LocalOfferIcon,
  RadioButtonChecked,
} from '@mui/icons-material';

export const iconMapping = {
  REF_ID: AssignmentOutlined,
  TYPE_ID: Business,
  TEXT: FormatAlignLeft,
  DATE: Event,
  OCR: FilterCenterFocus,
  TAGS: LocalOfferOutlined,
  STRING: ShortText,
  DOUBLE: LooksOne,
  BOOLEAN: Check,
  CHECKBOX: List,
  SELECT: ArrowDropdown,
  LOCATION: LocationOn,
  PEOPLE: PeopleIcon,
  PRIVACY_ID: SecurityIcon,
  PEOPLE_LIST: GroupIcon,
  SIGNATURE: DrawIcon,
  TIME: AccessTime,
  FILE_LIST: BurstMode,
  ARIS_CART: ViewListIcon,
  REFERENCE: AddLink,
  SCHEDULE: DateRange,
  TAGS_DROPDOWN: LocalOfferIcon,
  MULTIPLE_CHOICE: RadioButtonChecked,
};
