import { createTheme } from '@mui/material/styles';
import { designTokens } from './designTokens';
import ComponentsOverrides from './overrides';

const baseTheme = createTheme({
  palette: {
    primary: {
      main: designTokens.colors.primary.main,
      light: designTokens.colors.primary.light,
      dark: designTokens.colors.primary.dark,
      lighter: designTokens.colors.primary.lighter,
      darker: designTokens.colors.primary.darker,
      1: designTokens.colors.primary[1],
      2: designTokens.colors.primary[2],
      3: designTokens.colors.primary[3],
      4: designTokens.colors.primary[4],
      5: designTokens.colors.primary[5],
      6: designTokens.colors.primary[6],
      7: designTokens.colors.primary[7],
      8: designTokens.colors.primary[8],
      9: designTokens.colors.primary[9],
      10: designTokens.colors.primary[10],
    },
    secondary: {
      main: designTokens.colors.secondary.main,
      light: designTokens.colors.secondary.light,
      dark: designTokens.colors.secondary.dark,
      lighter: designTokens.colors.secondary.lighter,
      darker: designTokens.colors.secondary.darker,
      1: designTokens.colors.secondary[1],
      2: designTokens.colors.secondary[2],
      3: designTokens.colors.secondary[3],
      4: designTokens.colors.secondary[4],
      5: designTokens.colors.secondary[5],
      6: designTokens.colors.secondary[6],
      7: designTokens.colors.secondary[7],
      8: designTokens.colors.secondary[8],
      9: designTokens.colors.secondary[9],
      10: designTokens.colors.secondary[10],
      11: designTokens.colors.secondary[11],
    },
    background: {
      default: designTokens.colors.background.default,
      paper: designTokens.colors.background.paper,
      1: designTokens.colors.background[1],
      2: designTokens.colors.background[2],
      3: designTokens.colors.background[3],
      4: designTokens.colors.background[4],
      5: designTokens.colors.background[5],
    },
    text: {
      primary: designTokens.colors.text.primary,
      secondary: designTokens.colors.text.secondary,
    },
    divider: designTokens.colors.divider,
    grey: designTokens.colors.grey,
  },
  typography: {
    fontFamily: designTokens.typography.fontFamily,
    h1: designTokens.textStyles.heading.h1,
    h2: designTokens.textStyles.heading.h2,
    h3: designTokens.textStyles.heading.h3,
    h4: designTokens.textStyles.heading.h4,
    h5: designTokens.textStyles.heading.h5,
    h6: designTokens.textStyles.heading.h6,
    body1: designTokens.textStyles.body.medium,
    body2: designTokens.textStyles.body.small,
    button: designTokens.textStyles.button.medium,
    caption: designTokens.textStyles.caption,
    overline: designTokens.textStyles.overline,
  },
  spacing: designTokens.spacing.unit,
  breakpoints: {
    values: {
      xs: designTokens.breakpoints.xs,
      sm: designTokens.breakpoints.sm,
      md: designTokens.breakpoints.md,
      lg: designTokens.breakpoints.lg,
      xl: designTokens.breakpoints.xl,
    },
  },
  shape: {
    borderRadius: designTokens.borderRadius.standard,
  },
  customShadows: {
    button: designTokens.effects.shadows.button,
    text: designTokens.effects.shadows.sm,
    z1: designTokens.effects.shadows.sm,
    z2: designTokens.effects.shadows.md,
    primary: designTokens.effects.shadows.md,
    primaryButton: designTokens.effects.shadows.button,
    secondary: designTokens.effects.shadows.md,
    secondaryButton: designTokens.effects.shadows.button,
    error: designTokens.effects.shadows.md,
    errorButton: designTokens.effects.shadows.button,
    warning: designTokens.effects.shadows.md,
    warningButton: designTokens.effects.shadows.button,
    info: designTokens.effects.shadows.md,
    infoButton: designTokens.effects.shadows.button,
    success: designTokens.effects.shadows.md,
    successButton: designTokens.effects.shadows.button,
    grey: designTokens.effects.shadows.md,
    greyButton: designTokens.effects.shadows.button,
  },
});

export const muiTheme = createTheme(baseTheme, {
  components: ComponentsOverrides(baseTheme),
});